### ISSUE TITLE
呐，加窝一个吧

### ISSUE THREAD

**Issue by sg-first** [ice1000/AIAndroid#1]
窝是搞机器学习,另外把文档写一下吧

**Comment by sg-first** [comment]
嗷对主要是友人的算法文档

**Comment by ice1000** [comment]
他有弃坑的倾向，不过界面和框架我还是会老老实实地搭建的

**Comment by ice1000** [comment]
然后算法那块我们可以合作使用SQLite和JNI技术（你是什么语言的啊

**Comment by sg-first** [comment]
啥语言窝都能用其实（只有不是太反人类的

**Comment by sg-first** [comment]
他为啥弃坑

**Comment by ice1000** [comment]
因为AI算法太复杂，这几天他一直在研究哲学，脑子快坏了

**Comment by sg-first** [comment]
哲……哲学（希望达到啥效果

**Comment by ice1000** [comment]
呐，你该star了。。。因为我需要让它保持在首页第一个

**Comment by ice1000** [comment]
就是 人为什么会有思想？ 你是怎么理解语言的？你的思维的本质是什么？

**Comment by sg-first** [comment]
卧槽这是完全在重复造轮子吗（这人还能回归本态嘛其实只要勤劳姿势并不是问题（其实是我孤身一人搞一部分很快就没劲了

**Comment by Wimacs** [comment]
冰封没有理解我的正真意思，其实也不太需要包装成App，我的正真目的是想脱离一下符号主义，实验一下行为主义（也许这是将来强人工智能发展的方向吧），从人性的本质入手，脱离中文屋效应，制造一个有记忆，感知，自发思考的AI。

**Comment by sg-first** [comment]
…………什么是行为主义（在实现方向上看

**Comment by Wimacs** [comment]
就好比仿生吧

**Comment by sg-first** [comment]
大脑的话……到现在也没清楚是怎么运作的，应该没法完全仿生吧……

**Comment by sg-first** [comment]
如果你想说的是借鉴一些机制……可能你正在重新发明深度学习……

**Comment by Wimacs** [comment]
恩……差不多

**Comment by Wimacs** [comment]
还有，我说的是理想状态，冯氏计算机怎么弄得出强人工智能，所以……借鉴一些心理学方面的研究成果就可以啦。

**Comment by sg-first** [comment]
第一个先保留意见……第二个…心理学上和语言到思维反应相关的跨界（不是正统理论）部分大概是NLP（神经语言程序（不是自然语言处理））……但是这个目前我个人感觉大部分理论还是基于统计学的，单独拿出来还是个伪科学。所以落到最后还是放在统计学上。而且NLP进行的前提是理解语义（才能形成它所谓的“感觉信号”），但自然语言生成语法树基本已经被证明为不可行了。所以我感觉目前被学术界认可的方法，还是要落在统计学上。完全脱离现有框架发明理论的话……大概可能只有一些参考价值……
