### ISSUE TITLE
学习一下编译原理会很有用＝＝

### ISSUE THREAD

**Issue by lfkdsk** [ice1000/AIAndroid#3]

**Comment by sg-first** [comment]
= =parse 自然语言吗……

**Comment by lfkdsk** [comment]
可以试试啊=_=

**Comment by sg-first** [comment]
= =根据上世纪最后三十年的研究，这样是不行滴~

**Comment by lfkdsk** [comment]
不需要全部实现，能做简单的词法语法分析，有决策树能做一些处理就好的＝＝

**Comment by sg-first** [comment]
单说lexical的话……和NLP上的分词是有点相似。不过tokentype没法判断（非要对应的话应该类似于词性标注）自然语言里token的词性基本没法通过上下文判断状态转换来确认（要是这么干又掉进了写手写算一辈子都算不完的语法规则的大坑里TAT……）
最后决策树应对这种情况也完全无力啊= =除非实现就对每个句子都写好了答句，只是需要搜一下判断一下，不过这样的话感觉有点………………

**Comment by ice1000** [comment]
:fearful: 卧槽你们。。。其实现在我只是把这个当成文字游戏框架:joy:。。<br/>
还有@sg-first 滚去更新[PRG](https://github.com/ProgramLeague/PLASTIC_RPG)

另外，说到编译原理。。。我连算导都没看过啊。。。<br/>
这样也能学编译原理？:joy:

**Comment by sg-first** [comment]
冰封老板我最近忙着写小稿啊。。。等我回去更rpg窝会第一时间给您加头像挂readme

**Comment by lfkdsk** [comment]
@ice1000 Dialog写的好像有问题，莫名黑一块

**Comment by ice1000** [comment]
@lfkdsk 啥？哪里黑一块:joy:

**Comment by ice1000** [comment]
@sg-first 你可以去做关卡啊 我已经做了两个章节了 第三章地图完善 剧情还没做:joy:

**Comment by ice1000** [comment]
@sg-first 对了 你去把前面剧情部分的BGM去掉，换成自己的BGM，（就是那个什么Theme2）我想打包出尽可能小的安装包所以我修改了我本机的RM的RTP数据，现在打包出来你的剧情部分缺两首音乐，要闪退:joy:你把音乐换一下吧

**Comment by sg-first** [comment]
我踏马是干啥都没空啊，你没看群里水都没我了吗

**Comment by sg-first** [comment]
我已经把我身体的全部时间都献给了你的小稿

**Comment by ice1000** [comment]
然而我手机都没了:joy:

**Comment by anqur** [comment]
> 😨 卧槽你们。。。其实现在我只是把这个当成文字游戏框架😂。。
> 
> 还有@sg-first 滚去更新[PRG](https://github.com/ProgramLeague/PLASTIC_RPG)
> 
> 另外，说到编译原理。。。我连算导都没看过啊。。。
> 
> 这样也能学编译原理？😂

瞧我发现了什么 (

**Comment by ice1000** [comment]
> > 😨 卧槽你们。。。其实现在我只是把这个当成文字游戏框架😂。。
> > 
> > 还有@sg-first 滚去更新[PRG](https://github.com/ProgramLeague/PLASTIC_RPG)
> > 
> > 另外，说到编译原理。。。我连算导都没看过啊。。。
> > 
> > 这样也能学编译原理？😂
> 
> 瞧我发现了什么 (

你妈 (
